server:
    port: 8005
    servlet:
        context-path: "/academy"

spring:
    application:
        name: todoapp
    datasource:
        password: SuperSecret
        url: jdbc:h2:mem:todoappdb
        username: sa
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        show_sql: true